In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(
    filepath_or_buffer='data/youtube-ing.csv'
)

df.head()

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description
0,Jw1Y-zhQURU,17.14.11,John Lewis Christmas Ad 2017 - #MozTheMonster,John Lewis,26,2017-11-10T07:38:29.000Z,"christmas|""john lewis christmas""|""john lewis""|...",7224515,55681,10247,9479,https://i.ytimg.com/vi/Jw1Y-zhQURU/default.jpg,False,False,False,Click here to continue the story and make your...
1,3s1rvMFUweQ,17.14.11,Taylor Swift: …Ready for It? (Live) - SNL,Saturday Night Live,24,2017-11-12T06:24:44.000Z,"SNL|""Saturday Night Live""|""SNL Season 43""|""Epi...",1053632,25561,2294,2757,https://i.ytimg.com/vi/3s1rvMFUweQ/default.jpg,False,False,False,Musical guest Taylor Swift performs …Ready for...
2,n1WpP7iowLc,17.14.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10T17:00:03.000Z,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",17158579,787420,43420,125882,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...
3,PUTEiSjKwJU,17.14.11,Goals from Salford City vs Class of 92 and Fri...,Salford City Football Club,17,2017-11-13T02:30:38.000Z,"Salford City FC|""Salford City""|""Salford""|""Clas...",27833,193,12,37,https://i.ytimg.com/vi/PUTEiSjKwJU/default.jpg,False,False,False,Salford drew 4-4 against the Class of 92 and F...
4,rHwDegptbI4,17.14.11,Dashcam captures truck's near miss with child ...,Cute Girl Videos,25,2017-11-13T01:45:13.000Z,[none],9815,30,2,30,https://i.ytimg.com/vi/rHwDegptbI4/default.jpg,False,False,False,Dashcam captures truck's near miss with child ...

In [3]:
df.shape

(38916, 16)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38916 entries, 0 to 38915
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   video_id                38916 non-null  object
 1   trending_date           38916 non-null  object
 2   title                   38916 non-null  object
 3   channel_title           38916 non-null  object
 4   category_id             38916 non-null  int64
 5   publish_time            38916 non-null  object
 6   tags                    38916 non-null  object
 7   views                   38916 non-null  int64
 8   likes                   38916 non-null  int64
 9   dislikes                38916 non-null  int64
 10  comment_count           38916 non-null  int64
 11  thumbnail_link          38916 non-null  object
 12  comments_disabled       38916 non-null  bool
 13  ratings_disabled        38916 non-null  bool
 14  video_error_or_removed  38916 non-null  bool
 15  description             38304 non-null  object
dtypes: bool(3), int64(5), object(8)
memory usage: 4.0+ MB

In [5]:
df.columns

Index(['video_id', 'trending_date', 'title', 'channel_title', 'category_id',
       'publish_time', 'tags', 'views', 'likes', 'dislikes', 'comment_count',
       'thumbnail_link', 'comments_disabled', 'ratings_disabled',
       'video_error_or_removed', 'description'],
      dtype='object')

In [6]:
df.drop(
    columns=['thumbnail_link', 'comments_disabled', 'ratings_disabled', 'video_error_or_removed', 'description'],
    axis=1,
    inplace=True
)

df.head()

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count
0,Jw1Y-zhQURU,17.14.11,John Lewis Christmas Ad 2017 - #MozTheMonster,John Lewis,26,2017-11-10T07:38:29.000Z,"christmas|""john lewis christmas""|""john lewis""|...",7224515,55681,10247,9479
1,3s1rvMFUweQ,17.14.11,Taylor Swift: …Ready for It? (Live) - SNL,Saturday Night Live,24,2017-11-12T06:24:44.000Z,"SNL|""Saturday Night Live""|""SNL Season 43""|""Epi...",1053632,25561,2294,2757
2,n1WpP7iowLc,17.14.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10T17:00:03.000Z,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",17158579,787420,43420,125882
3,PUTEiSjKwJU,17.14.11,Goals from Salford City vs Class of 92 and Fri...,Salford City Football Club,17,2017-11-13T02:30:38.000Z,"Salford City FC|""Salford City""|""Salford""|""Clas...",27833,193,12,37
4,rHwDegptbI4,17.14.11,Dashcam captures truck's near miss with child ...,Cute Girl Videos,25,2017-11-13T01:45:13.000Z,[none],9815,30,2,30

In [7]:
(
    df.groupby(by='title')
        .agg({
            'views': ['sum', 'mean'],
            'likes': ['sum', 'mean'],
            'dislikes': ['sum', 'mean'],
            'comment_count': ['sum', 'mean']
        })
)

                                                       views                \
                                                         sum          mean
title
#21 How to go FAST!!! Coaching famous youtuber ...     47358  1.578600e+04
#ConanHaiti Preview: Haitians Roast Trump  - CO...   5953602  4.579694e+05
#GameOn - 88 Seconds of Video Games                  4691181  4.264710e+05
#KIISCampus Surprise with BTS | On Air with Rya...   1817099  1.514249e+05
#Laurel? #Yanny? Or...                               9875181  6.583454e+05
...                                                      ...           ...
인피니트(INFINITE) Tell Me Teaser #D-6. SUNGKYU           121549  1.215490e+05
청하 (CHUNGHA) - Roller Coaster MV                    39792610  2.842329e+06
한국 컵라면+소주를 처음 먹어본 동계올림픽 전설들의 반응!                    46211536  1.320330e+06
🔥  'Avengers: Infinity War' Cast Answer Your Bu...   9432999  8.575454e+05
🔥  The 'Avengers: Infinity War' Cast Play ‘HOT ...   6175569  6.175569e+05

                                                      likes                 \
                                                        sum           mean
title
#21 How to go FAST!!! Coaching famous youtuber ...     2052     684.000000
#ConanHaiti Preview: Haitians Roast Trump  - CO...   135580   10429.230769
#GameOn - 88 Seconds of Video Games                  136912   12446.545455
#KIISCampus Surprise with BTS | On Air with Rya...   117440    9786.666667
#Laurel? #Yanny? Or...                               190239   12682.600000
...                                                     ...            ...
인피니트(INFINITE) Tell Me Teaser #D-6. SUNGKYU           16980   16980.000000
청하 (CHUNGHA) - Roller Coaster MV                    1935927  138280.500000
한국 컵라면+소주를 처음 먹어본 동계올림픽 전설들의 반응!                     809687   23133.914286
🔥  'Avengers: Infinity War' Cast Answer Your Bu...   183317   16665.181818
🔥  The 'Avengers: Infinity War' Cast Play ‘HOT ...   126805   12680.500000

                                                   dislikes               \
                                                        sum         mean
title
#21 How to go FAST!!! Coaching famous youtuber ...       24     8.000000
#ConanHaiti Preview: Haitians Roast Trump  - CO...    19709  1516.076923
#GameOn - 88 Seconds of Video Games                    2112   192.000000
#KIISCampus Surprise with BTS | On Air with Rya...      419    34.916667
#Laurel? #Yanny? Or...                                91964  6130.933333
...                                                     ...          ...
인피니트(INFINITE) Tell Me Teaser #D-6. SUNGKYU              30    30.000000
청하 (CHUNGHA) - Roller Coaster MV                      25640  1831.428571
한국 컵라면+소주를 처음 먹어본 동계올림픽 전설들의 반응!                      14701   420.028571
🔥  'Avengers: Infinity War' Cast Answer Your Bu...     2101   191.000000
🔥  The 'Avengers: Infinity War' Cast Play ‘HOT ...     1497   149.700000

                                                   comment_count
                                                             sum         mean
title
#21 How to go FAST!!! Coaching famous youtuber ...           422   140.666667
#ConanHaiti Preview: Haitians Roast Trump  - CO...         21484  1652.615385
#GameOn - 88 Seconds of Video Games                         8384   762.181818
#KIISCampus Surprise with BTS | On Air with Rya...          8052   671.000000
#Laurel? #Yanny? Or...                                     55926  3728.400000
...                                                          ...          ...
인피니트(INFINITE) Tell Me Teaser #D-6. SUNGKYU                 1158  1158.000000
청하 (CHUNGHA) - Roller Coaster MV                           95850  6846.428571
한국 컵라면+소주를 처음 먹어본 동계올림픽 전설들의 반응!                           79635  2275.285714
🔥  'Avengers: Infinity War' Cast Answer Your Bu...          6065   551.363636
🔥  The 'Avengers: Infinity War' Cast Play ‘HOT ...          4609   460.900000

[3369 rows x 8 columns]

In [ ]:
# Task: "tags" sütununda ki veriler parçalanıp sayılarak "tag_count" isimli yeni bir sütuna yazdırılacak
# Path I

# def calculate_tags(tag: str) -> int:
#     return len(tag.split('|'))

# df['tag_count'] = df['tags'].apply(calculate_tags)

# df[['title', 'tags', 'tag_count']]

,title,tags,tag_count
0,John Lewis Christmas Ad 2017 - #MozTheMonster,"christmas|""john lewis christmas""|""john lewis""|...",9
1,Taylor Swift: …Ready for It? (Live) - SNL,"SNL|""Saturday Night Live""|""SNL Season 43""|""Epi...",36
2,Eminem - Walk On Water (Audio) ft. Beyoncé,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",6
3,Goals from Salford City vs Class of 92 and Fri...,"Salford City FC|""Salford City""|""Salford""|""Clas...",9
4,Dashcam captures truck's near miss with child ...,[none],1
...,...,...,...
38911,Enrique Iglesias - MOVE TO MIAMI (Official Vid...,"Enrique Iglesias feat. Pitbull|""MOVE TO MIAMI""...",4
38912,Jacob Sartorius - Up With It (Official Music V...,"jacob sartorius|""jacob""|""up with it""|""jacob sa...",41
38913,Anne-Marie - 2002 [Official Video],"anne|""marie""|""anne-marie""|""2002""|""two thousand...",17
38914,Eleni Foureira - Fuego - Cyprus - LIVE - First...,"Eurovision Song Contest|""2018""|""Lisbon""|""Cypru...",8
38915,KYLE - Ikuyo feat. 2 Chainz & Sophia Black [A...,"Kyle|""SuperDuperKyle""|""Ikuyo""|""2 Chainz""|""Soph...",18

In [4]:
# Path II
df['tag_count'] = df['tags'].apply(lambda x: len(x.split('|')) if pd.notna(x) else 0)

df[['title', 'tags', 'tag_count']]

,title,tags,tag_count
0,John Lewis Christmas Ad 2017 - #MozTheMonster,"christmas|""john lewis christmas""|""john lewis""|...",9
1,Taylor Swift: …Ready for It? (Live) - SNL,"SNL|""Saturday Night Live""|""SNL Season 43""|""Epi...",36
2,Eminem - Walk On Water (Audio) ft. Beyoncé,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",6
3,Goals from Salford City vs Class of 92 and Fri...,"Salford City FC|""Salford City""|""Salford""|""Clas...",9
4,Dashcam captures truck's near miss with child ...,[none],1
...,...,...,...
38911,Enrique Iglesias - MOVE TO MIAMI (Official Vid...,"Enrique Iglesias feat. Pitbull|""MOVE TO MIAMI""...",4
38912,Jacob Sartorius - Up With It (Official Music V...,"jacob sartorius|""jacob""|""up with it""|""jacob sa...",41
38913,Anne-Marie - 2002 [Official Video],"anne|""marie""|""anne-marie""|""2002""|""two thousand...",17
38914,Eleni Foureira - Fuego - Cyprus - LIVE - First...,"Eurovision Song Contest|""2018""|""Lisbon""|""Cypru...",8
38915,KYLE - Ikuyo feat. 2 Chainz & Sophia Black [A...,"Kyle|""SuperDuperKyle""|""Ikuyo""|""2 Chainz""|""Soph...",18

In [7]:
# tag_count 30'dan büyük olan içerikleri yazdırın
df.query("tag_count > 30")[['title', 'tags', 'tag_count']].sort_values(by='tag_count', ascending=False)

,title,tags,tag_count
20147,부부싸움중인 강아지들 (사람이랑 완전 똑같음ㅋㅋㅋ),"doggy|""dog""|""shiba""|""shibainu""|""puppy""|""pet""|""...",78
19330,부부싸움중인 강아지들 (사람이랑 완전 똑같음ㅋㅋㅋ),"doggy|""dog""|""shiba""|""shibainu""|""puppy""|""pet""|""...",78
19732,부부싸움중인 강아지들 (사람이랑 완전 똑같음ㅋㅋㅋ),"doggy|""dog""|""shiba""|""shibainu""|""puppy""|""pet""|""...",78
20751,부부싸움중인 강아지들 (사람이랑 완전 똑같음ㅋㅋㅋ),"doggy|""dog""|""shiba""|""shibainu""|""puppy""|""pet""|""...",78
19528,부부싸움중인 강아지들 (사람이랑 완전 똑같음ㅋㅋㅋ),"doggy|""dog""|""shiba""|""shibainu""|""puppy""|""pet""|""...",78
...,...,...,...
35789,Mission: Impossible - Fallout (2018) - Officia...,"Official Trailer|""Movie""|""New Movie""|""Film""|""O...",31
16003,SHOULD I HAVE A HOME BIRTH?,"jamie and nikki|""family vlog""|""daily vlog""|""be...",31
15999,"Bhad Bhabie Hi Bich Remix Feat. Rich The Kid, ...","world star hip hop|""worldstarhiphop""|""worldsta...",31
6498,Carson Wentz Gets Injured Vs Rams Torn ACL,"Carson Wentz injury|""carson wentz""|""eagles""|""c...",31
19946,Hereditary | Official Trailer HD | A24,"a24|""a24 films""|""a24 trailers""|""independent fi...",31

In [10]:
# en yüksek tag sayısına sahip 10 içerik

df.sort_values(by='tag_count', ascending=False).head(10)[['title', 'tags', 'tag_count']]

,title,tags,tag_count
19732,부부싸움중인 강아지들 (사람이랑 완전 똑같음ㅋㅋㅋ),"doggy|""dog""|""shiba""|""shibainu""|""puppy""|""pet""|""...",78
20956,부부싸움중인 강아지들 (사람이랑 완전 똑같음ㅋㅋㅋ),"doggy|""dog""|""shiba""|""shibainu""|""puppy""|""pet""|""...",78
21161,부부싸움중인 강아지들 (사람이랑 완전 똑같음ㅋㅋㅋ),"doggy|""dog""|""shiba""|""shibainu""|""puppy""|""pet""|""...",78
20751,부부싸움중인 강아지들 (사람이랑 완전 똑같음ㅋㅋㅋ),"doggy|""dog""|""shiba""|""shibainu""|""puppy""|""pet""|""...",78
19932,부부싸움중인 강아지들 (사람이랑 완전 똑같음ㅋㅋㅋ),"doggy|""dog""|""shiba""|""shibainu""|""puppy""|""pet""|""...",78
19137,부부싸움중인 강아지들 (사람이랑 완전 똑같음ㅋㅋㅋ),"doggy|""dog""|""shiba""|""shibainu""|""puppy""|""pet""|""...",78
21370,부부싸움중인 강아지들 (사람이랑 완전 똑같음ㅋㅋㅋ),"doggy|""dog""|""shiba""|""shibainu""|""puppy""|""pet""|""...",78
20147,부부싸움중인 강아지들 (사람이랑 완전 똑같음ㅋㅋㅋ),"doggy|""dog""|""shiba""|""shibainu""|""puppy""|""pet""|""...",78
20549,부부싸움중인 강아지들 (사람이랑 완전 똑같음ㅋㅋㅋ),"doggy|""dog""|""shiba""|""shibainu""|""puppy""|""pet""|""...",78
19528,부부싸움중인 강아지들 (사람이랑 완전 똑같음ㅋㅋㅋ),"doggy|""dog""|""shiba""|""shibainu""|""puppy""|""pet""|""...",78

In [12]:
# (likes / (likes + dislikes)) formülü üzerinden hesaplanarak like_avg sütununa yazalım

def calculate_like_avg(likes: int, dislike: int) -> float:
    if (likes + dislike) == 0:
        return 0.0
    return likes / (likes + dislike)

df['like_avg'] = df.apply(
    lambda row: calculate_like_avg(row['likes'], row['dislikes']),
    axis=1
)

df.sort_values(by='like_avg', ascending=False).head(10)[['title', 'likes', 'dislikes', 'like_avg']]

,title,likes,dislikes,like_avg
36631,Kris Wu – Like That (Official Music Video),57544,0,1.0
7088,HIGHLIGHTS: MK Dons U18s 1-0 Cardiff City U18s,30,0,1.0
5361,QUIZ : Name the Trail : A Christmas Cracker,2,0,1.0
12082,Lima Sopoaga Tribute🔥🔥||The Unsung Hero||💯 2017,50,0,1.0
5338,Bohemian Rhapsody (2018) - Scene Bohemian Rhap...,71,0,1.0
7939,HIGHLIGHTS: MK Dons U18s 1-0 Cardiff City U18s,32,0,1.0
12090,Wild About Argyll,66,0,1.0
14940,Maisie Williams is going to be Game of Thrones...,43,0,1.0
12977,Wild About Argyll,80,0,1.0
37653,Kris Wu – Like That (Official Music Video),96167,0,1.0

In [ ]:
# Path II

df['like_avg'] = df['likes'] / (df['likes'] + df['dislikes'])
df['like_avg'] = df['like_avg'].fillna(0)

df.sort_values(by='like_avg', ascending=False).head(10)[['title', 'likes', 'dislikes', 'like_avg']]

,title,likes,dislikes,like_avg
36631,Kris Wu – Like That (Official Music Video),57544,0,1.0
7088,HIGHLIGHTS: MK Dons U18s 1-0 Cardiff City U18s,30,0,1.0
5361,QUIZ : Name the Trail : A Christmas Cracker,2,0,1.0
12082,Lima Sopoaga Tribute🔥🔥||The Unsung Hero||💯 2017,50,0,1.0
5338,Bohemian Rhapsody (2018) - Scene Bohemian Rhap...,71,0,1.0
7939,HIGHLIGHTS: MK Dons U18s 1-0 Cardiff City U18s,32,0,1.0
12090,Wild About Argyll,66,0,1.0
14940,Maisie Williams is going to be Game of Thrones...,43,0,1.0
12977,Wild About Argyll,80,0,1.0
37653,Kris Wu – Like That (Official Music Video),96167,0,1.0

In [ ]:
# (likes / (likes + dislikes)) formülü üzerinden hesaplanarak like_avg sütununa yazalım

def calculate_like_avg(likes: pd.Series, dislike: pd.Series) -> list:
    like_list = list(likes)
    dislike_list = list(dislike)

    combined_list = list(zip(like_list, dislike_list))

    avg_list = []

    for like, dislike in combined_list:
        if (like + dislike) == 0:
            avg_list.append(0.0)
        else:
            avg = like / (like + dislike)
            avg_list.append(round(avg, 2))
    
    return avg_list

df['like_avg'] = calculate_like_avg(likes=df['likes'], dislike=df['dislikes'])

df[['title', 'likes', 'dislikes', 'like_avg']].sort_values(by=['like_avg', 'likes'], ascending=[False, False])

,title,likes,dislikes,like_avg
36739,BTS (방탄소년단) 'FAKE LOVE' Official MV (Extended ...,1437859,6390,1.0
34312,BTS (방탄소년단) 'FAKE LOVE' Official Teaser 2,1431730,6335,1.0
22179,j-hope 'Airplane' MV,1401920,6268,1.0
34147,BTS (방탄소년단) 'FAKE LOVE' Official Teaser 2,1290509,4358,1.0
24302,"CRISTIANO RONALDO E FRED, O GRANDE ENCONTRO",1257242,6311,1.0
...,...,...,...,...
38214,This Is America: Women's Edit,0,0,0.0
38382,This Is America: Women's Edit,0,0,0.0
38555,This Is America: Women's Edit,0,0,0.0
38730,This Is America: Women's Edit,0,0,0.0
38900,This Is America: Women's Edit,0,0,0.0

In [20]:
# kanalların like_avg nedir?

df.groupby(by='channel_title', as_index=False) \
  .agg({
      'like_avg': 'mean',
      'comment_count': 'sum'
  }) \
  .assign(like_avg=lambda x: x['like_avg'].round(2)) \
  .sort_values(
      by='comment_count',
      ascending=False
  ) \
  .head(10)

             channel_title  like_avg  comment_count
1516               ibighit      0.99       42026951
758       Logan Paul Vlogs      0.78       33078023
1532      jypentertainment      0.96       15703519
236    ChildishGambinoVEVO      0.94       15441941
1446     YouTube Spotlight      0.75       14262175
829   Marvel Entertainment      0.97       11525772
998              PewDiePie      0.94        9560538
342              DrakeVEVO      0.97        9225778
1111                SMTOWN      0.99        8407734
78        ArianaGrandeVevo      0.96        7869276